---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_PATH}:/sonarr_config
      - ${DATA_PATH}:/tv #optional
      - ${DATA_PATH}:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - local_network

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_PATH}:/radarr_config
      - ${DATA_PATH}:/movies #optional
      - ${DATA_PATH}:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - local_network

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_PATH}:/prowlarr_config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - local_network

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${CONFIG_PATH}:/deluge_config
      - ${DATA_PATH}:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
