---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_PATH}sonarr_config:/config
      - ${DATA_PATH}tv:/tv
      - ${DATA_PATH}downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - local_network

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_PATH}radarr_config:/config
      - ${DATA_PATH}movies:/movies
      - ${DATA_PATH}downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - local_network

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_PATH}prowlarr_config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - local_network

  deluge:
    image: binhex/arch-delugevpn
    container_name: deluge
    cap_add:
      - NET_ADMIN
    ports:
      - "8112:8112"
      - "8118:8118"
      - "58846:58846"
      - "58946:58946"
    volumes:
      - ${CONFIG_PATH}deluge_config:/config
      - ${DATA_PATH}downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VPN_ENABLED=yes
      - VPN_PROV=airvpn
      - VPN_CLIENT=openvpn
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=info
      - DELUGE_ENABLE_WEBUI_PASSWORD=yes
      - DEBUG=false
      - VPN_INPUT_PORTS=1234
      - VPN_OUTPUT_PORTS=5678
      - UMASK=000
    restart: unless-stopped
    networks:
      - local_network

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    ports:
      - "32400:32400"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ${CONFIG_PATH}plex_config:/config
      - ${DATA_PATH}tv:/tv
      - ${DATA_PATH}movies:/movies
    restart: unless-stopped
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
